### ISSUE TITLE
Super Laser can only be fired once

### ISSUE THREAD

**Issue by Phyoog** [mocsarcade/starjunk#108]
Just what it says on the tin.

Easily replicable, get the super laser, fire it. You can't fire again.

**Comment by codaventure** [comment]
I have `this.powerUp.cooldown.time++` and `this.powerUp.reload.time++` in the wrong places in the `Junkership` class. The way I have it now it only updates on the `justDown` and `isDown` events respectively, whereas the timers should update on every frame. The reason it's not noticeable for reload is because you're allowed to hold the fire button and have it update every frame, but logically it still needs moved. This should fix it.
